# Generated by Django 5.2.7 on 2025-10-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='food_item',
            field=models.BooleanField(default=True),
        ),
    ]
