# Generated by Django 5.2.7 on 2025-10-31 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_sale_food_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='food_item',
        ),
    ]
