# Generated by Django 5.2.7 on 2025-10-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('veg', models.BooleanField(default=True)),
                ('unit', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
